services:
   browser-worker:
    build: .
    container_name: browser-worker
    restart: unless-stopped
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    environment:
      - PORT=${PORT:-3001}
      - BROWSERLESS_URL=${BROWSERLESS_URL:-ws://browserless:3000}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN:-secret}
    networks:
      - browser-worker

networks:
  browser-worker:
    driver: bridge
