services:
  browser-worker:
    build: .
    container_name: browser-worker
    restart: unless-stopped
    platform: linux/amd64
    shm_size: 2gb
    mem_limit: 6g
    ports:
      - ${PORT:-3001}:${PORT:-3001}
